<?php
/**
 * Created by PhpStorm.
 * User: Eric
 * Date: 2018/4/28
 * Time: 17:23
 */

namespace app\back\model;
use think\Db;

class Admin extends Base
{
    protected $autoWriteTimestamp = true;
   // protected $updateTime =false;
    // 定义时间戳字段名
   // protected $createTime = 'login_time';
   // protected $updateTime = 'update_at';

    //创建修改器,将密码自动sha1加密存储
    public function setPasswdAttr($val)
    {
        return sha1($val);
    }
    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        self::afterInsert(function ($admin){
            $uid = $admin->id;
            $group_id = input('post.group_id');
            //dump($group_id);exit;
            $data['uid'] = $uid;
            $data['group_id'] = $group_id;
            Db::name('auth_group_access')->insert($data);
        });
        self::beforeUpdate(function ($admin){
           $data['uid'] = $uid = $admin->id;
           $data['group_id'] = input('post.group_id');
            Db::name('auth_group_access')->where('uid',$uid)->update($data);
        });
        self::beforeDelete(function ($admin){
            $uid = $admin->id;
            if(!is_array($uid))
                Db::name('auth_group_access')->where('uid',$uid)->delete();
            else
                Db::name('auth_group_access')->where('uid','in',$uid)->delete();
        });
    }

    //
    public function getAdminList()
    {
        $lst = Db::name('admin')->alias('a')
            ->field('a.id,a.username,a.passwd,g.title,a.create_time,a.update_time,a.is_use')
            ->join('auth_group_access ga','ga.uid = a.id')
            ->join('auth_group g','g.id = ga.group_id')
            ->paginate(5);

        return $lst;
    }
}