<?php

namespace app\back\model;
use think\Db;
use think\Model;
use think\Collection;

class Goods extends Model
{
    protected $autoWriteTimestamp = true;
    protected  $updateTime = false;
    protected  static  function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Goods::beforeInsert(function ($goods){
            //处理上传
            $path = ROOT_PATH.'public'.DS.'uploads';
            $ext = ['size'=>12323,'ext'=>'jpg,png,gif'];
            $file_rule = 'uniqid';
            $goods->uploads($goods,'goodsImg',$ext,$file_rule,$path);

        });
    }
    public function getList()
    {
        return $list = Goods::where('isDel',1)->order('id')->paginate(5);

    }
    /*
     * 文件上传
     */

   public function uploads($goods,$filname,$thumb,$file_rule,$path)
   {

       $img = request()->file($filname);

       if(empty($img)) return false;


       $info = $img->validate($thumb)->rule($file_rule)->move($path);
       if($info)
       {
           $file_name = $info->getSaveName();
           $goods[$filname] = $file_name;

          return bkReturn('上传成功',1) ;
       }
       else
       {
           return $img->getError();
       }


   }




}
