<?php
/**
 * Created by PhpStorm.
 * User: Eric
 * Date: 2018/4/19
 * Time: 11:01
 */

namespace app\back\controller;


use think\Controller;


class Base extends  Controller
{
 protected function _initialize()
 {
     parent::_initialize(); // TODO: Change the autogenerated stub
      //define('ADMIN_ID',Session::set('admin_id'));
     if(!\session('admin_id')) $this->error('请先登录','Login/index');
 }




}