<?php
/**
 * Created by PhpStorm.
 * User: Eric
 * Date: 2018/4/28
 * Time: 23:13
 */

namespace app\back\controller;
use app\back\model\Privileges as pM;
use think\Db;
class Privileges extends Base
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $model = model('privileges');
        $privi = $model->getTree();
        $this->assign('privi',$privi);
    }

    public function index()
    {
        return $this->fetch('rule');
    }
    public function add()
    {

        if(request()->isPost())
        {
            if(model('privileges')->add())
            {
                $this->success('添加成功','privileges/index');
            }
            else
            {
                $this->error('添加失败');
            }
        }

        return $this->fetch('privi_add');
    }
    public function edit($id)
    {

        if(request()->isPost()) {
            $edit = model('privileges')->edit();
            if ($edit) {
                $this->success('修改权限成功！', url('index'));
            } else {
                $this->error('修改权限失败！');
            }
        }
        $privi_list = model('privileges')->find($id);
        $child = model('privileges')->getChildren($id);
        //dump($child);
        $this->assign('child',$child);
        $this->assign('privi_list',$privi_list);
        $this->assign('id',$id);
        return $this->fetch('privi_edit');
    }
    public function delete($id)
    {
        $p = model('privileges');
        $ro =  model('role')->field('id,rules')->select();
        $ids = $p->getChildren($id);
        $ids[] = (int)$id;
        foreach ($ro as $k => $v)
        {
            $rules = explode(',',$v['rules']);
            if(  $diff = array_diff($rules,$ids))
            {
                $diff = implode(',',$diff);
                Db::name('auth_group')->where('id',$v['id'])->setField('rules',$diff);
            }

        }

        return  pM::destroy($ids) ? ['message'=>'成功','status'=>1] : ['message'=>'失败','status'=>0];

    }


}